name: CI

on:
    pull_request:
        branches:
            - 'master'
    push:
        branches:
            - 'master'

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Install Node
                uses: actions/setup-node@v4
                with:
                    node-version: '20.x'

            -   name: Install dependencies
                run: npm ci

            -   name: Running tests
                run: npm run test:coverage

            -   name: Upload to Coveralls
                uses: coverallsapp/github-action@v2
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}

    build:
        name: Build
        needs: test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Install Node
                uses: actions/setup-node@v4
                with:
                    node-version: '20.x'

            -   name: Install dependencies
                run: npm ci

            -   name: Build
                run: npm run build

            -   name: Save artifact
                uses: actions/upload-artifact@v4
                with:
                    name: dist
                    path: dist/

    release:
        name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Install Node
                uses: actions/setup-node@v4
                with:
                    node-version: '20.x'
                    registry-url: 'https://registry.npmjs.org'

            -   name: Load artifact
                uses: actions/download-artifact@v4
                with:
                    name: dist
                    path: dist/

            -   name: Release
                run: npm run release

            -   name: Publish to NPM
                run: npm publish --access public
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
